# Generated by Django 2.0.4 on 2018-04-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='event',
            name='num_of_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
