# Generated by Django 2.0.4 on 2018-04-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180421_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment',
        ),
    ]
