# Generated by Django 2.0.4 on 2018-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180425_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='num_of_attendees',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
