# Generated by Django 2.0.4 on 2018-05-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180428_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
