# Generated by Django 2.0.4 on 2018-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180516_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profiles'},
        ),
    ]
